Fix for BOWC-1092
libsv/paymail-server pull request #3
Opened 2022-02-04 20:01 UTC by sirdeggen

Associate Paymail with User ID - /api/alias allows blank body and just creates a paymail "" to point to a new user ID with no profile.

Expected :  /api/alias should not allow registering empty paymail aliases nor allow profiles without at minimum and email and name. Error 400 otherwise.

2022-02-07 13:29 UTC, Tigh-Gherr requested changes
Just some error casing to sort, will approve once done

2022-02-07 13:29 UTC, Tigh-Gherr commented on data/payd/payd.go
> +		return nil, errors.New("Must include name and email for user registration.")
Can start with lower case as per the rationale here https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2151

2022-02-07 13:29 UTC, Tigh-Gherr commented on service/alias.go
> +		return nil, errors.Wrap(err, "User creation failed")
error casing

2022-02-07 13:29 UTC, Tigh-Gherr commented on service/alias.go
> +		return nil, errors.Wrap(err, "Alias creation failed")
error casing

2022-02-08 23:33 UTC, sirdeggen commented
> Just some error casing to sort, will approve once done

@Tigh-Gherr please may I request another glance - fixes done and another capability added that's actually potentially useful this time - rather than a dummy.

2022-02-09 15:08 UTC, Tigh-Gherr approved these changes
LGTM!

2022-02-10 13:29 UTC, merged